### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by shawmanz32na** [idelsink/webdav-docker#3]
I'm running idelsink/webdav from a docker-compose configuration on Docker for Windows (18.03.0-ce, build 0520e24).

`docker-compose.yml`:
```
version: '3'

services:
  webdav:
    image: idelsink/webdav
    environment:
      - USERNAME=webdav
      - PASSWORD=vadbew
    ports:
      - '8081:80'
    volumes:
      - '.webdav:/webdav'
```

I'm using WinSCP (5.13.1, build 8265) to interact with the container. Using WinSCP, I can connect to `http://localhost:8081` using `webdav`/`vadbew`, and can navigate the files and download them. However, when trying to upload a file to the directory, WinSCP fails, reporting `500 internal server error`

![image](https://user-images.githubusercontent.com/5596570/38520732-78c7559c-3bf8-11e8-8aca-49e4488d3e2d.png)

I attached to the container and viewed the apache logs, and I see these lines:
```
[Mon Apr 09 20:10:19.385323 2018] [dav:error] [pid 18] [client 172.18.0.1:33560] The locks could not be queried for verification against a possible "If:" header.  [500, #0]
[Mon Apr 09 20:10:19.385349 2018] [dav:error] [pid 18] [client 172.18.0.1:33560] Could not open the lock database.  [500, #400]
[Mon Apr 09 20:10:19.385355 2018] [dav:error] [pid 18] (2)No such file or directory: [client 172.18.0.1:33560] Could not open property database.  [500, #1]
```
